### ISSUE TITLE
Report cell "Result" column data when none

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#101]
I specifically selected "Not checked" but the report says "No result" -- so this is a mismatch.

Option 1:
* "Not checked" is the default in the drop-down (as is).
* "Not checked" is displayed in the report (instead of "No result").

Option 2:
* The drop-down default is blank.
* The report cell is blank -- or "none" in lighter gray text -- but I think blank would make it easier to see what's not done yet.

Right now I prefer option 1 -- could be convinced otherwise. :)

**Comment by hidde** [comment]
Hm, I think this is a bug:

* if you select ‘Failed’, then select ‘Not checked’, it will display it as ‘Not checked’ in the report.
* there is code in place that marks an SC as “evaluated” as soon as something is selected
* it seems that code does not trigger if you select the same option that is already selected (ie the default). This may be tricky to fix.

Suggestion: we can fix this by having ‘--’ as the first option, so that any selection, including ‘Not checked’ triggers a change.
