### ISSUE TITLE
Too much included in success criteria heading 

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-atag-report-tool#113]
The success criteria heading includes the Success Criteria number, name, levels and a link to the implementing document.

I don't know that all of this is necessary. I think they only thing in the heading should be the Success Criteria number and name. The other items are secondary information and most likely will just add clutter for some users.

**Comment by hidde** [comment]
I agree there is a lot of information, and would prefer less, but we do have rationale for each.

## Name

This seems essential, agreed it should be in the header.

## Level

* Level is important, because some auditors organise their feedback by level.
* Level also matters specifically, because in ATAG, which the group decided to want to follow closely, some criteria offer a choice in which level to apply (“multi-level SCs”, which we're working on UI for in #95). 
* Level used to be underneath criterion text, but has moved to the top level in https://github.com/w3c/wai-atag-report-tool/issues/104, to make levels easier to scan.

To make it less cluttery and easier to scan, I have made the level smaller and, with that, styled differently than the heading  text. I'm open to other ways to avoid clutter here, maybe we can revisit #104 and move it back to be underneath the criterion.

## Link to implementing

The rationale here is that the criterion text, which the group decided to not change and include literally, can be confusing and is, or so we assume, unfamiliar to most accessibility experts. For those reasons, we want to make it easy to quickly find more information.

With that in mind, would you suggest this link to exist somewhere else, by styled differently, or go away completely?

## SC number

This seems useful to some, agreed it should be in the header.

**Comment by iadawn** [comment]
The SC number and name are the main 'heading' information everything else is hierarchically below the heading.

I am not convinced that the visual styling to reduce clutter is sufficient to reduce clutter for all users. 

The visual styling is fine, I think it is the underlying semantics that are the problem.

I would propose the heading only contain the SC number and name. Everything else should be in a paragraph or div element.

**Comment by hidde** [comment]
> The visual styling is fine, I think it is the underlying semantics that are the problem.
> 
> I would propose the heading only contain the SC number and name. Everything else should be in a paragraph or div element.

Apologies, I did not realise you were talking semantics, I agree and will update the `h3` to just contain name and number.
