### ISSUE TITLE
first page instructions

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#126]
Hidde and Shawn talked about making this better meet the range of users, especially the extremes &mdash; **which will likely to make up most of users**:
1. know ATAG and don’t want to read much before getting started using the tool.
2. don’t know much at all about ATAG and want to learn about this tool.

Hidde,
Another thought I had when going over the other open issues and our discussion: On the Report page I think we'll now have:
* "This report has results for X out of 63 Success Criteria."
* List of each Result with (XX) and list of SCs -- including which SCs are "Not checked"

I think most users will find that *very* useful. They'll will want to check the Report page periodically throughout doing their evaluation and the report.

Therefore, I suggest including something about that on the first page -- probably in the minimal "How to use this tool section". Maybe something like: "As you use the tool, the Report page lists the success criteria that you have checked and not checked. You can get to it from the last item in the navigation bar, "Report"."

**Comment by hidde** [comment]
First pass at this in PR #128 ([all changes](https://github.com/w3c/wai-atag-report-tool/pull/128/commits/84ed9560503709899abf42e5be7987e0e3635981)).

> You can go back and forth between the pages (each is a Principle) in any order. None of the fields are required.

Removed this, following our discussion yesterday.

> More information on each ATAG Success Criterion

Moved to “Structure of this tool” section.

I've added “As you use the tool, the Report page lists the success criteria that you have checked and not checked.”, instead of the explanation I turned “Report page” into a link, do you think that would be sufficient?

Feel free to make changes to the [Pull Request](https://github.com/w3c/wai-atag-report-tool/pull/128) too. [`routes/Overview.svelte`](https://github.com/w3c/wai-atag-report-tool/blob/master/src/routes/Overview.svelte) is mostly HTML.

**Comment by slhenry** [comment]
> I've added “As you use the tool, the Report page lists the success criteria that you have checked and not checked.”...

**I cannot see where that sentence is added? I think it should be the first bullet under "Tips for using this tool:"**

> ...instead of the explanation I turned “Report page” into a link, do you think that would be sufficient?

Hum, yes, that enables them to get it from this sentence; however, what about later when they are on an SC page? I feel *mildy* that it would be good to give that instruction -- only mildly and fine if as Editor you don't want to.

**Comment by hidde** [comment]
> I cannot see where that sentence is added? I think it should be the first bullet under "Tips for using this tool:"

Not sure what happened, I thought I had added it, but I had not. Have just added as first item.

> Hum, yes, that enables them to get it from this sentence; however, what about later when they are on an SC page? I feel mildy that it would be good to give that instruction -- only mildly and fine if as Editor you don't want to.

I'd rather leave it out, while this takes more figuring out on the part of the user, it makes the explanation shorter.
