### ISSUE TITLE
Report - Results - Overview missing Result Options

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#132]
location: Report Page, under h2 Results, under h3 Overview
Issue: the list of Results is incomplete

Not sure if this is bug or intended?

Right now if none of the SCs have a Result selected, then none of the Result options are listed, and if only one Result option is selected, then only that one shows up.

I think **all Result options should always be visible**.

**Comment by nitedog** [comment]
I think you are referring to the summary of SCs above the table on that page? In that case, I agree.

**Comment by hidde** [comment]
Thanks, will update. 

I think we should also remove “out of 63 Success Criteria” (63 is the number of total ATAG criteria, and only relevant if the evaluation target is AAA). 

I think we should include, as discussed in EOWG, the total items missed that are within evaluation target. So, with a target of AA, it would show all items that were not evaluated, and are Level A or Level AA.

**Comment by hidde** [comment]
Have done an update to this with the following changes:

* Removed links to evaluated success criteria - Hidde and Shawn discussed there is likely less need to link to these, because these are already done. 
* Displayed evaluated success criteria differently, with larger number and all on one line, so that it takes less space, is easier to scan and somewhat visually interesting
* Added missing items in an expand collapse, followed pattern from WAI website (heading in `summary`). For these, I tried the tag-like “success criterion” styling, but resorted to plain old links. Added name of criterion in addition to just the number. Put in two columns on larger viewports.

What I tried, but removed: 

* Color numbers based on their result color (green for passed, red for failed etc). Too busy. 
* Create a tab for each category (Passed, failed, etc), then display all SCs for each category. Too many links, only few useful (the missing ones).

<img width="754" alt="27 passed, 7 failed, 3 cannot tell, 1 not applicable, 1 not checked, with the numbers large and green and the words right underneath" src="https://user-images.githubusercontent.com/178782/84264956-5c0fd280-ab22-11ea-805b-23b20d24c3c6.png">


<img width="777" alt="expand collapse heading that says missing results; it is expanded, underneath a long bullet list with a link in each list item" src="https://user-images.githubusercontent.com/178782/84264868-3edb0400-ab22-11ea-895f-e308d75a8637.png">

**Comment by nitedog** [comment]
Following EOWG discussion "Not Checked" (according to EARL) is intended for success criteria that are in scope but have not yet been checked.

**Comment by hidde** [comment]
Tasks for Hidde following the EOWG meeting: 

* [ ] Make the categorie names slightly bigger so that they're easier to spot
* [ ] Rename '--' to “Not Checked”, remove “Not checked”
* [ ] Remove “Not Checked” category from summary
* [ ] Rename “Missing Results” to “Not Checked”, add amount, i.e. “Not Checked (3)”
* [ ] In Results table, remove “No results” as that's now just “Not Checked”
* [ ] Find out if we can improve explanation of “Cannot tell”

What we decided not to do: 

* List out of scope (rationale: “Not Checked” is like a to do list, out of scope items don't provide the same value, as they've become less relevant when a scope was selected that didn't include them)
* Link to or list specific items in any of the already evaluated categories (Passed, Failed, Cannot Tell, Not Applicable)

**Comment by hidde** [comment]
This has now been updated! 

Throughout the tool, where it says “X out of Y items”, we refer to items _within_ conformance target. So, if your target is Level A and you evaluate an SC in Level AA, that does not count towards your X _or_ Y.
