### ISSUE TITLE
"View in report" link

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#138]
With each Observations input field, there is a "View in report" link.

I think that's good.

Some tweaks:

* [x] The link should go to that section of the report. (I think just bug that not doing that now.)

* [x] Should be capitalized as:
> View in Report

* [x] It's missing affordance that it's a link.
   * [x] At a minimum, it should be link color, not heading color.
   * One could say it should be underlined, or have an icon, or something else to signal "LINK". I'm inclined to say it doesn't need anything else because: 1. The text content "View in Report" signals that it goes to the Report, 2. it's not essential.<BR>Others thoughts?

**Comment by hidde** [comment]
Thanks! 

>  The link should go to that section of the report. (I think just bug that not doing that now.) 

Confirming this is a bug, I broke this last week, will fix!

**Comment by hidde** [comment]
Have capitalised.

The link is underlined. I have removed the green color, this was for consistency with the labels, but that no longer applies. It now uses the standard WAI link color.

**Comment by hidde** [comment]
Fixed the “jump to the right section” bug in https://github.com/w3c/wai-atag-report-tool/commit/1297f72deb1bacff28bbabee381c86412331c2b3. This was tricky, because we actually had double IDs for each of the results, of which one was hidden and used by the “download as HTML” functionality. Removed double IDs (and also classes, aria-labelledby attributes).
