### ISSUE TITLE
[HTML Report] not display empty meta fields

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-atag-report-tool#148]
I mildly think fields like website, evaluator, etc. should not be in the final HTML report if they were left empty.

Exception: tool name -- it should be apparent if this is missing.

**Comment by hidde** [comment]
Have written the code to remove empty meta fields.

Can we not have an exception for tool name? This makes it hard to understand what is happening, as it creates a subjective distinction between meta fields. I feel it makes sense that if people choose not to fill in a tool name, that it does not show up in the report.

**Comment by nitedog** [comment]
I can live with that but question why -- I cannot imagine a use-case of preparing [even parts of] an evaluation report without a tool name. I think it is a good reminder in this case that this is missing, if the user does not provide a tool name.

**Comment by hidde** [comment]
> I can live with that

Ok, thanks for the feedback! 

> I cannot imagine a use-case of preparing [even parts of] an evaluation report without a tool name

Me neither, so I think people will not leave it empty.

Validation may be helpful, but unless we rely on browser / HTML5 validation (which we previously decided not to, because error message not as accessible as we want it to be), it is a whole new rabbit hole when it comes to implementation for little gain,  because it's likely people will fill it in, and if they don't, that's not the end of the world.
