### ISSUE TITLE
With X of XX, add "Level A" or "Level A and AA"

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#153]
From https://github.com/w3c/wai-atag-report-tool/issues/60#issuecomment-644167550

>> Note, throughout the tool, when we say “X out of Y items”, we only count items within conformance target.

> Would be good to note that in the user documentation (on the fist page).

I have an even better idea (I think:)! Just **make it clear with X of XX** (then don't need to add to documentation :)

Also, I think can shorten "X out of XX" to just "X of XX".

So in Evaluation Box, it would be either:
* "Reported on # of 24 Level A success criteria."
* "Reported on # of 52 Level A and AA success criteria."
* "Reported on # of 63 success criteria."

I think don't need "Level A, AA, AAA" in the last one. Although I'd be fine with it if others think so.

**Comment by hidde** [comment]
That's smart! 
 
Mockup:

<img width="240" alt="Reported on 26 out of 26 Level A and AA Success Criteria" src="https://user-images.githubusercontent.com/178782/84819025-acea6400-b017-11ea-9969-5507e6e8143c.png">

Maybe a smaller font size is in order so that it comfortably fits the most common (assuming that's _Level A and Level AA)):

<img width="245" alt="Reported on 26 out of 26 Level A and AA Success Criteria smaller font size" src="https://user-images.githubusercontent.com/178782/84819041-b378db80-b017-11ea-807b-f234465cea96.png">

I wonder if “success criteria” should come first as it is slightly more important than level? What about: 

* "Reported on # of 24 success criteria (Level A)."
* "Reported on # of 52 success criteria (Level A, AA)." 

<img width="246" alt="Reported on 26 out of 26 success criteria (Level A, AA)." src="https://user-images.githubusercontent.com/178782/84819312-15d1dc00-b018-11ea-8f9d-e2872e92629e.png">

(used comma instead of “and” so that it fits on two lines in most common scenario)

Agree that with a AAA conformance target, it needs no clarification.

**Comment by slhenry** [comment]
Note above:
> Also, I think can shorten "X out of XX" to just "X of XX".

I think having the levels at the end is a bit more cludgy. Also uses more characters.

I _mildly_ think it's smoother to say:
"Reported on # of 24 Level A success criteria"
"Reported on # of 52 Level A and AA success criteria"
and OK to use comma instead of "and" for:
"Reported on # of 52 Level A, AA success criteria"

Also nice to have the number and the Level next to each other, since that's what changes.

You could get rid of the period at the end to save a character, if you wanted.

**Comment by hidde** [comment]
> Note above:

>> Also, I think can shorten "X out of XX" to just "X of XX".

Woops, missed that. Agreed.

> I mildly think it's smoother to say:
> "Reported on # of 24 Level A success criteria"
> "Reported on # of 52 Level A and AA success criteria"
> and OK to use comma instead of "and" for:
> "Reported on # of 52 Level A, AA success criteria"

Ok, will take that suggestion. 

> You could get rid of the period at the end to save a character, if you wanted.

Played with this, seems it does not matter. for the length.

**Comment by hidde** [comment]
Fixed in https://github.com/w3c/wai-atag-report-tool/commit/6deadc5b8768df8b56d2d5daddecfc41cbc9d92b
