### ISSUE TITLE
progress bar contrast

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#154]
I want to note this for the record. After @hidde and @nitedog see it, I think can close.

A quick check of the contrast in the progress bar gives:
* pale-wai-green on gray (completed indication) = 4:1
* blueish-gray on gray (incomplete indication) = 1.4:1

I think this is fine (and good) here, because the information in the bars is redundant with the text (# of #) and that text has contrast of 14.7:1

(We just need to clearly document when we put that component in WAI site design, that it must be accompanied with strong contrast redundant information. :-)

**Comment by nitedog** [comment]
Or somehow indicate the maximum length of the progress bar?

**Comment by hidde** [comment]
Good find! Maybe in the component design, we can have explicitly two versions: if there is accompanying text, it's this, if there is not, it's a high contrast version. So that users of the component will be reminded.

I think maximum length is clear as it is the width of the column? Agree with @slhenry that this current use is fine as there is text.

**Comment by nitedog** [comment]
If there will be a version with sufficient contrast then why not just always use that?

**Comment by hidde** [comment]
Because it would be less subtle and grab more attention.

**Comment by hidde** [comment]
Closing as  per @slhenry opening comment (“After @hidde and @nitedog see it, I think can close”)
