### ISSUE TITLE
field border bug

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#161]
When I tab out of the Website field, it has keeps a red highlight border:

![image](https://user-images.githubusercontent.com/6991814/85176189-dcc78080-b23e-11ea-812c-515131640481.png)

**Comment by hidde** [comment]
This is a browser feature that happens when users entered anything that's not a URL (we're using [a `url` input field](https://html.spec.whatwg.org/dev/input.html#url-state-(type=url))).

An added benefit of using a URL input field is that some devices will display a different keyboard (for instance, an iPad might display the keyboard that has a '.com' button and no space bar). I think this improves accessibility for at least some users.

We have extended the field label to explicitly set the expectation with `(URL)` so that there is explanation for the red border.
