### ISSUE TITLE
[ED-low] HTML download table formatting

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#165]
![image](https://user-images.githubusercontent.com/6991814/85331217-59ef3180-b49b-11ea-82ee-c0d6237e40d9.png)

Would you do just a little more to make the table easier to read?
* all cells: align top and left
* make spacing around text in cells consistent, with some padding so text is not too close to borders.<br>(currently there is no spacing if no observations. and the current spacing before and after the text when there are observations could be less.)
* (minor) quieter border lines, e.g., color:#3b3b3b

(follow on to https://github.com/w3c/wai-atag-report-tool/issues/72 )

**Comment by hidde** [comment]
I feel we should display this without styles, so with the browser defaults, because when we start adding styles, we'll probably want to add more and more.

Following your comments, I've made these changes:

* align all cells top and left
* make spacing in cells `1em`. The reason for this is that `<p>`'s get usually that in the UA stylesheet, and we have `<p>`'s in the observations cell. Adding it to all other cells, makes it consistent. This does not address “current spacing could be less”, but to address that we'd also need to override UA-stylesheet-provided spacing for all elements that Markdown can generate, that seems would overcomplicate this and be more work to remove for an end user that wants to provide their own styling
* use `#3b3b3b` as border color

cc @nitedog
