### ISSUE TITLE
[ED-low][minor] spacing between label and field

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#166]
**(This is _teeny little minor_ thing that I wasn't going to comment on, but it keeps niggly me. )**

(A) This seem just right:
![image](https://user-images.githubusercontent.com/6991814/85332306-55c41380-b49d-11ea-9bff-374e87a19d4b.png)

(B) Here I think too much space between the label and the field boxes:
![image](https://user-images.githubusercontent.com/6991814/85332168-0c73c400-b49d-11ea-873e-79bce0d8ee7b.png)

_Edit: added (A) and (B) - Hidde_

**Comment by hidde** [comment]
I feel there is too little space between label and input in (A) The extra space in (B) gives the user some breathing room and makes the UI calmer and with that, easier to take in.

Currently, (A) is per [WAI Design Components](https://wai-website-theme.netlify.app/components/form/elements/). 

Proposal: we update WAI Design Components to increase whitespace, like in (B), so that it is all consistent.

**Comment by hidde** [comment]
Thinking about it… in (A) the whitespace is mostly between the form elements, we could do the same in (B).

**Comment by hidde** [comment]
In (B), I have increased whitespace between elements, decreased between label and input so that it is more per styleguide.

<img width="691" alt="" src="https://user-images.githubusercontent.com/178782/85385766-f7ea0700-b542-11ea-8167-b841729d8299.png">
