### ISSUE TITLE
Replace short handle in page heading with actual ATAG Principle

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-atag-report-tool#58]
This is part of issues #56 and #57 but also an issue of it's own:

Most of the text comes from ATAG directly, except for the Principles, which is confusing to me. Especially the link "More details: ..." seems misleading because there is actually no more details for the Principle, just the Guidelines and Success Criteria which are included in the tool anyway.

I think it would be much clearer to simply use the ATAG Principle as is without the subsequent link, because it would be much clearer that all the text is simply from ATAG itself.

That is, instead of saying:

> # UI operable
> More details: [A.3 Editing-views are operable](https://www.w3.org/TR/ATAG20/#principle_a3)

Simply have:

> # A.3: Editing-views are operable

**Comment by hidde** [comment]
I think this change would make the tool harder to scan for users who are not ATAG experts. Shorter names with minimal jargon (and if jargon is used, only the most widely used words) would be ideal from the user's point of view.

**Comment by hidde** [comment]
To add to my previous comment, this is a screenshot of what that would look like in the first step, for extra effect I have also added A.1.1 to the SC, so that now each part (Principle, Guideline, SC) is numbered. 

I am extremely concerned this will make people give up and close their tab and quit the accessibility team. 

<img width="1309" alt="" src="https://user-images.githubusercontent.com/178782/79763060-d80c4c00-8323-11ea-8e2b-13fb78ef56bc.png">

**Comment by nitedog** [comment]
I'm personally not convinced that coming up with new vague wording, like "Accessibility Guidelines" in this case, makes the tool more usable. I'll go with the majority opinion.

**Comment by hidde** [comment]
I believe better handles can dramatically increase usability (and usage) of this tool, my recommendation is to stay away from the ATAG handles.

If the majority would prefer exact ATAG handles, I am of course happy to make the change.

Adding this to the agenda for discussion.

**Comment by hidde** [comment]
@nitedog @slhenry 

We discussed at EO Plan that we could go for shorter names, as long as the words are at least in the original principle name, and does not introduce new jargon (like “UI” instead of “Editing-views”).

We want to: 

* not rewrite ATAG (to avoid ending up with two standards)
* avoid very long titles (to allow easier scannability)

I believe this is trivial for all but B1. That leads me to these titles: 

| Full principle | Shorter principle |  
| ------------- | -----------------|
| A.1 Authoring tool user interfaces follow applicable accessibility guidelines | A.1: Accessibility Guidelines | 
| A.2 Editing-views are perceivable | A.2: Perceivable |
| A.3 Editing-views are operable | A.3. Operable |
| A.4 Editing-views are understandable |  A.4: Understandable |
| B.1 Fully automatic processes produce accessible content  |  B.1: Generated Content Accessible |
| B.2 Authors are supported in producing accessible content |  B.2: Authors Supported | 
| B.3 Helps with improving the accessibility of existing content |  B.3: Helps Improve Accessibility | 
| B.4 Promotes and integrates accessibility features |  B.4: Promotes Accessibility Features |

(this is how they are currently implemented: [ATAG Report Tool prototype](https://atag-report-tool.hdv.now.sh/))

Welcoming suggestions and/or +1's!

**Comment by nitedog** [comment]
I like these!

For B.1, I'm wondering about "Produce Accessible Content"? Seems closer to the actual title and similarly long.

**Comment by hidde** [comment]
With “Generated Content” I tried to summarise “fully automatic processes produce”, as opposed to content produced in some other (manual?) way. 

With just “Produce”, we may lose that, but maybe that was overly precies, and this actually sufficiently suggest that this is automatic. 

What about “Produces Accessible Content”, so that the tool is the subject of the sentence, and it is in line with “Helps” (B.3) and “Promotes” (B.4)?

**Comment by nitedog** [comment]
Yup. Fits well with "B.3 Helps..." and "B.4 Promotes...". Actually this makes "B.2 Authors Supported" stand out a little but I'm not going to mention that in public ;-)

**Comment by hidde** [comment]
“Supports authors”?
