### ISSUE TITLE
"Your Evaluation" page name seems confusing

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-atag-report-tool#59]
The name of the page "Your Evaluation" seems confusing (in the navigation and main heading). Unfortunately I don't have a better suggestion at the moment.

**Comment by hidde** [comment]
What about “About evaluation” or “Set up evaluation” or “Evaluation details”?

**Comment by nitedog** [comment]
I think these suggestions capture the meaning much better but don't click for me. Sorry, I'm having difficulty suggesting something useful here. I wonder what others think.

**Comment by hidde** [comment]
Same, adding to agenda for discussion.

**Comment by bakkenb** [comment]
I think the current "Start" page name should be changed to "Overview" because that is what it is. 

And then the current "Your Evaluation" page name can be changed to "Start Evaluation" or "Basic Information." 

The term "Basic Information" is what we use for this type of data in the [Developing an Accessibility Statement](https://www.w3.org/WAI/planning/statements/generator/#create) resource.

**Comment by bakkenb** [comment]
Another idea...

If we model it after the design of the [WCAG EM Report Tool](https://www.w3.org/WAI/eval/report-tool/#!/#%2F) navigation interface that includes the arrow looking buttons, then we could use the following:

| **Start** > **Basic Information** > **A.1** > **A.2** > **A.3** > **A.4** > **B.1** > **B.2** > **B.3** > **B.4** > **View Report** |

**Comment by hidde** [comment]
I think Overview is a great alternative for Start. I also really like the idea of going with “Basic Information” and keeping that consistent with our existing resources. We may have users that use both tools, they'll have less to learn. 

Personally, I would be keen on moving away from the arrow-like design, so that we suggest less about order (because people are free to start at the Report page, or jump straight into a specific Principle, especially if editing an existing/imported report).

**Comment by slhenry** [comment]
[EOWG telecon discussion 24 April](https://www.w3.org/2020/04/24-eo-minutes.html#item01)

**Comment by hidde** [comment]
Have implemented “Overview”, “Start”, “Report” for now, as it seems to have the most support from EOWG.
