### ISSUE TITLE
Add more meta fields to "Start” page

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-atag-report-tool#65]
I suggest adding the following metadata as well (all optional):

- Version of authoring tool
- Release date of authoring tool
- Date of evaluation

**Comment by hidde** [comment]
HB also requested:

*  version of report 

as metadata.

(I created #82, will close in favour of this issue.)

**Comment by nitedog** [comment]
Just wondering: how often is "version of report" used in real life as opposed to "date of evaluation"?

**Comment by hidde** [comment]
Seems like there is at least overlap in the use case? Will reach out to HB.

**Comment by HelenBurge** [comment]
I think date/version of the report should be one field but free text. Some will prefer dates and some (if amending a report on the same date might want to add time or a version). That way we do not add too many fields but allow the user to choose how they differentiate the reports.

**Comment by hidde** [comment]
@HelenBurge thanks, that makes sense.

@nitedog What do you think of, instead of “Evaluation date”, having one “Version” field that people can use for differentiating (with a date, number of however they like)?

**Comment by nitedog** [comment]
I like the idea but needs to be clearly separate from tool version.

**Comment by slhenry** [comment]
> I think date/version of the report should be one field but free text. Some will prefer dates and some (if amending a report on the same date might want to add time or a version).

+1

> I like the idea but needs to be clearly separate from tool version.

+1

Maybe:
> **Evaluation Date/Version:**

brainstorming... maybe it even **more open** and with suggestions. Maybe something like
> **Evaluation Status:** _(can be date completed, a version number, or other)_

**Comment by hidde** [comment]
What about “Your reference”? Can be a date, can be a version number, or some number obtained from some internal system.

**Comment by bakkenb** [comment]
"Your reference" is to vague.

Not sure I like Report Version field. To me I would just add my multiple report version numbers to the name of the report tool, but I would need to know up front that I was going to come back multiple times to create multiple reports on the same tool after iterative development work. 

I would like to see a mock up of the current existing and suggested fields to see what is intuitive and what fields would need some explanation as to what they are for. If too much explanation is needed for any one field then I think we need to drop the field or come up with a better name for it.

**Comment by slhenry** [comment]
more brainstorms...
> Reviewer Notes:
> Evaluation Notes:

... ???

**Comment by hidde** [comment]
> "Your reference" is to vague.

I think the field name would have to be vague (as in, it cannot be specific), because it allows for multiple ways of identifying (like version, like date and like a number from an internal system). 

The alternative, as I see it, would be to have specific fields for each of those types of identifiers, that solves the vagueness problem, but creates too many fields. I think one vague field is the least confusing option.

> more brainstorms...
>
> >  Reviewer Notes:
> >  Evaluation Notes:

“Notes” seems to me like it would be a text area, one or more sentences, where I think what we are after here is something that uniquely refers or identifies a specific evaluation?

**Comment by nitedog** [comment]
I like the idea of "Reviewer Notes" and "Evaluation Notes". In the WCAG-EM Report Tool, you can provide an "Executive Summary" and "Record of Evaluation Specifics" (such as screen-shots or other helpful information collected during the evaluation). The latter is part of WCAG-EM but the "Executive Summary" was added to the report tool, to help create better reports (usually reports have such a summary). Having said that, these fields are probably better put at the end of the evaluation process rather than the beginning.

**Comment by hidde** [comment]
To clarify, do you mean “Reviewer Note” / “Evaluation Notes” as a field meant to assign a unique reference to a report, like “Version” or “Report date”? 

Or are you suggesting this field to exist in addition to the “unique reference” field? If so, I agree, and would suggest we call it “Executive Summary” or “Management Summary”, as I feel that would be the most common name. I would prefer to have this at the start, so that there is only one page of meta fields and not two.

**Comment by lakeen** [comment]
I think a Notes field would be very useful.  I don't have strong feelings about what the label should be. Management or Executive Summary works also.

**Comment by daniel-montalvo** [comment]
I am in favor of more metadata fields in the first page. Adding a separate page at the end with such fields would make the resource a bit convoluted for me.

I understand the point of giving the reviewer/evaluator some room with open-ended names such as "Review notes" or "Evaluator notes". However, if we put only these I am afraid we would be missing sight of what we are specifically asking for: the internal or unique reference to identify this report later on.

In this case I would go for two specific fields such as "Version of the tool", "Date of the evaluation".

**Comment by HelenBurge** [comment]
"Reference"  could be a good label for the generic field, but still be meaningful.

**Comment by bakkenb** [comment]
Agree with Daniel...
> However, if we put only these I am afraid we would be missing sight of what we are specifically asking for: the internal or unique reference to identify this report later on.

Personally I would rather have fields that ask for specific detail so I know what to put in them.

Then also provide a "Notes" field like Laura mentions. "Notes" is specific, but lets you put any notes you would like to add. People generally understand what a Notes field is for (speaking from U.S. perspective).

**Comment by AndrewArch** [comment]
Comments from colleagues:
- Dates tested
- Technologies used (for testing or in the product)
- Conformance target (there’s an issue for this in Github already)
- some statistics gathered from the pass/fail dropdowns from each criteria, which could maybe go into the suggested Executive Summary feature if that goes ahead

**Comment by slhenry** [comment]
For the "unique identifier":
* it will be optional
* good to leave it open format so people can use whatever they want
* date of evaluation – I think date is good metadata to include – maybe that’s enough for the “unique identifier”
* other brainstorm:
** report identifier

**Comment by hidde** [comment]
Following EOWG discussion on 15 May: Hidde to prototype having editable fields on the Report page, one for executive summary and one for unique idenitifier which is the date initially but can be edited to be anything.

**Comment by hidde** [comment]
I've experimented with this today, and concluded what we want does not be coherent. 

1. On the current Report page, all fields are read-only, editing happens elsewhere (in 'Start' page or on the relevant Principle page).
2. If we add a Report Identifier field and an Executive Field, the Report page is now a mix of read-only and editable fields. Some of those are only editable on the Report page, others are editable elsewhere.

**Comment by hidde** [comment]
After more discussion, it seems neither of the above are ideal. Exec summary at the start is confusing, because you'd summarise a report you've not created yet, an editable exec summary  at the end is odd if it is the only editable thing.

We should probably combine these. New proposal below.

## Default vs edit mode

We could have two views: default vs edit. When someone lands on the Report page, they see the “read-only” / default mode.

<img width="658" alt="" src="https://user-images.githubusercontent.com/178782/83647216-f4530800-a5b4-11ea-8b92-dfcf3dd8885b.png">

When they click “edit”, the section goes into “edit” mode.

<img width="653" alt="" src="https://user-images.githubusercontent.com/178782/83647989-d1752380-a5b5-11ea-97ef-bdfa1ecf07fd.png">

The difference is: instead of the values, we show inputs (that contain the values if they are provided). Underneath, we display a “Save” (return to default mode; does not actually save, as technically the value is saved whenever it is changed).

**Comment by slhenry** [comment]
+1 to both display or editable on the Report page!

Minor: Maybe EOWG folks can brainstorm something more descriptive than "General"?
Maybe "About this Evaluation"?

Also, I think Executive Summary can go in this section -- yet, I'm totally fine if others prefer it as a separate section.

**Comment by hidde** [comment]
Preview of editable on report page: https://atag-report-tool-pnmz196ur.now.sh/report 

Looking forward to suggestions for “General”. I like “About” or “About this Evaluation”.
