### ISSUE TITLE
[bug] forward/back button on "Your Evaluation" page

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-atag-report-tool#67]
At the bottom of the screen, there is no back button and the forward button is to "Step 1" rather than the actual page title.

**Comment by hidde** [comment]
The concept of this is that we want people to start the process, not go back. 'Step 1' identifies the start of a process better than the page title, because “step” is a more widely used phrase than the name of an ATAG principle. Users can still go back to the start page in various ways (with browser back button or with the navigation at the top).

**Comment by nitedog** [comment]
It seems that the label for the forward button has now been fixed on this page. It now works better for me but I still find it quite odd that there is a forward button from the "Start" page to "Your Evaluation" page but not back. Seems inconsistent to me but I don't feel strongly.

**Comment by hidde** [comment]
Have updated this!
