### ISSUE TITLE
[minor] Is "ATAG REPORT TOOL (X/Y)" unnecessary?

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-atag-report-tool#68]
Above every main heading, we have "ATAG REPORT TOOL (X/Y)", which seems unnecessary to me. If the main point of this is to indicate progress, maybe this is better done differently? Note also issue #61 about visual progress indication (maybe also combined with the navigation being a numbered list)?

**Comment by slhenry** [comment]
(X/X) not needed. It's clear enough from the nav bar.

**Comment by hidde** [comment]
I think it is useful, because it reiterates that this is a process with steps, and where a user is in that process.

Yes, that information is in the nav bar, and yes, it would be clear to people who know ATAG by heart and realise they're being taken through ATAG (or have read the info on the Overview page), but I think it is likely not everyone will.

Proposal:

* Keep “ATAG Report Tool” as it is the only place on the page where the name of this tool is displayed (except for the browser title bar, but these are more and more obscured in most browsers, especially for users with many tabs).
* Use “x of y” for more clarity (this is the text in the source code already, the / is just visual)

**Comment by slhenry** [comment]
+1 to keeping "ATAG Report Tool" somewhere. I'm fine with where it is visually. I haven't checked where it is non-visually... [/me has another idea and will open a separate issue...]

-1 to (X of X)

**overall:** I don't feel strongly about this. While I do think it's unnecessary and thus is visual cutter and cognitive clutter, I also think that's _very minor_, so if EOWG decides it's useful, I'm OK with that.

**More info:**

I still think that "where I am and what I have to do" is clear in the nav bar, and so (X of X) is not needed.

> it would be clear to people who know ATAG by heart and realise they're being taken through ATAG (or have read the info on the Overview page), but I think it is likely not everyone will.

Anyone using this tool will need to realize at least that, even if they previously didn't know ATAG.

> process with steps

I thought were didn't want to emphasize that it is a process with steps -- and instead make it comfortable for users to do it in any order?

**And another point:** the current implementation does not match my mental model.

> ATAG Report Tool (3/8) _or_ ATAG Report Tool (3 of 8)

In fact, there are **_s_ pages of the ATAG Report Tool**, not 8.

If this number indicates the 8 Principles, then it should be with the Principle text, not with "ATAG Report Tool".

**Comment by hidde** [comment]
Basically, the first and last pages of ART aren't part of the “process”… ha, now you point it out I do see how this makes little sense. Unless, maybe, the 8 steps look visually different somehow, but that would probably also over complicate things.

Still curious what others think, but you've convinced me that `3/8` should probably go somewhere else (or away).

**Comment by bakkenb** [comment]
Personally I think this is not needed. It is intuitive enough without it.
