### ISSUE TITLE
link to "Implementing X.Y.Z" not sufficiently clear as a link

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-atag-report-tool#69]
To me, the rounded shading around the "Implementing X.Y.Z" seem more like a button or tag function rather than a link (to an external resource)?

**Comment by hidde** [comment]
I would like to use this visual treatment for links to success criteria and sections in accessibility specifications and plan to add it to our [Design Components](https://wai-website-theme.netlify.com/components/). 

If we manage to consistently use it (I do in the Authoring Tools List, and would also like to use it in the Techniques/Understanding redesign), we can help users identify these types of links more easily, because they get a consistent visual treatment that is different from other links.

**Comment by nitedog** [comment]
Why not reuse existing treatments/styles (eg. from QuickRef or other WAI pages)?

**Comment by hidde** [comment]
QuickRef is ‘old’ WAI styling, the redesigned WAI site has no treatment for this yet, so this would introduce just that (as a reusable thing for all WAI properties).

The intended benefit of this, as compared to making everything regular looking links, is that consistently applied visual difference can aid scanning.

**Comment by hidde** [comment]
Proposal: keep it as it is.

**Comment by iadawn** [comment]
I would be strongly against the proposed styling.

I don't think the visual affordance is strong enough. I would suggest the inclusion of a information icon to emphasise the additional content. This is more of a blend between the old and the new.

**Comment by hidde** [comment]
Is the below what we mean by 'old'?

<img width="163" alt="info icon, text Understanding 1.1.1" src="https://user-images.githubusercontent.com/178782/82449851-212ef780-9aac-11ea-88cc-045d31ae17c5.png">

In QuickRef, I noticed in the source that this is what we call button. 

The closest we have to a button in our [Design Components](https://wai-website-theme.netlify.app/components/) is the [Button](https://wai-website-theme.netlify.app/components/atoms/buttons/) and it comes with a small variant and an icon variant.

So maybe we can do something like this:

<img width="124" alt="magnifying glass icon, text button" src="https://user-images.githubusercontent.com/178782/82450167-a2868a00-9aac-11ea-9116-dca023cdf814.png">

but with a info icon instead of a magnifying glass icon.

**Comment by iadawn** [comment]
I am assuming that is what you meant by 'old' when you first referenced it. I don't know that the icon button fits the bill. That seems to be repurposing a component in a different way. If you were looking at the styling included in ART for the Implementing links as a new design element it is more about developing that pattern appropriately.

It may be that there it has two uses; one which requires the icon as it isn't as clear cut that it is a a link.

**Comment by hidde** [comment]
@iadawn I think it makes sense to, as you say, develop it as a new design element. There are design elements for this same purpose in the QuickRef tool, but that uses our “old” design, as opposed to our “2019 WAI website redesign”, which my current implementation tries to follow.

The current implementation is to put in a tag-like design. Some rationale: 

* tags signify a thing belongs to a thing, in this case the implementing page belongs to this success criterion
* an underline, I feel, would make it more prominent / attention-seeking, so I opted for no underline
* this design matches what we do in the Authoring Tools List, and could do in various other places, too, to hopefully make it easier for users to find sources related to the thing they're looking at.
* as a user, I would try and click on it or tab to it, as it would make sense to me that it is a link. That may not be the case for others. 

I still support current implementation, but am more than happy to look at alternatives. What do people think we should do instead? 

cc @iadawn, @nitedog, @slhenry

**Comment by hidde** [comment]
Example with link underlined: 

<img width="959" alt="Screenshot of success criterion, with implementing link not look like a tag, but like regular text with underline" src="https://user-images.githubusercontent.com/178782/83273867-479c1380-a1cd-11ea-82e7-f42f0cbda9db.png">

I would recommend not to go for that, because I feel it less clearly identifies “related source” and looks to similar to everything else. If anyone does feel this is better, let's discuss it in the group to see where consensus lies.

**Comment by nitedog** [comment]
This works better for me than the initial design. However, I think it may be good to indicate that the link takes the user away from the context of the tool, like maybe an arrow. It would also be nice to have some more visual design but I don't feel strongly about that at all.

**Comment by hidde** [comment]
Hidde discussed with Shawn, will update design to be more like “Understanding” links in QuickRef, with icon, white background and subtle border color, but have the rounded corners of [buttons the new WAI website](https://wai-website-theme.netlify.app/components/atoms/buttons/).

**Comment by slhenry** [comment]
Looking at the tool more, I think it would it make sense to have the same treatment for the Principle links, e.g., what is now: "More details: A.1 Authoring tool user interfaces follow applicable accessibility guidelines" -- yes?

**Comment by hidde** [comment]
Agreed! 

I've reused our [Small Secondary Button](https://wai-website-theme.netlify.app/components/atoms/buttons/#small-secondary-button), and made it lighter (`1px` border instead of `2px` and `normal` font weight instead of `bold`).

Preview: https://atag-report-tool-ljoh5rlgb.now.sh/

**Comment by hidde** [comment]
This is what that looks like: <img width="672" alt="Screenshot where links to ATAG Principle and SC Implementing page are styled with round solid border, white background and info icon" src="https://user-images.githubusercontent.com/178782/83792885-0196f200-a69c-11ea-94a8-483d62453e65.png">

It made me wonder if it would be better to list just the principle there, like “A.1” rather than the full name:

<img width="539" alt="Principle link with just A.1 no t the full name" src="https://user-images.githubusercontent.com/178782/83792989-29865580-a69c-11ea-947a-442c1b31e858.png">

**Comment by slhenry** [comment]
> It made me wonder if it would be better to list just the principle there, like “A.1” rather than the full name:

I think we want the full name because we want the text there to provide more description.

**Comment by slhenry** [comment]
From Hidde & Shawn discussion: quieter gray border and blackish text -- more like old QuickRef *yet* with colors from the new design palette

**Comment by hidde** [comment]
This is now added!

**Comment by slhenry** [comment]
hey Hidde. I'm getting a colored border and too light gray text.
Maybe it's a caching issue?

QuickRef link style is:
(text) color: #333
border-color: #ccc

Using new site colors, I think would be:
(text) color: #1d1d1d (or possibly #3b3b3b)
border-color: #ddd

Also, I note in QuickRef, it's smaller -- and I support that for this one, too
font-size: 0.8125rem  -- or whatever we're using for smaller size in new design

(Eric wanted me to re-open issues when I had additional comments. Let me know if that's not what you want.)

**Comment by hidde** [comment]
Hi Shawn, thanks for the feedback! I missed setting a color on the border, it was green-ish. Have updated it to be #3b3b3b for the text #ddd for the border (which is called “line grey” in our CSS so that seems a perfect fit). Have added the hover that is in quickref, with a gray background, let me know if you're not a fan and I'll remove it.

I have also improved alignment with the Level indication:

* They had a slightly different font size ( `.8125rem` which computed to `13.33px`, vs `smaller` which computed to `13px`). Have updated the level indication to match, because the button size is set in WAI CSS, so they're both `13.333px`.
* I aligned them vertically 

I think this is better, feel free to reopen again!

**Comment by slhenry** [comment]
Perfect! Great! that also addresses https://github.com/w3c/wai-atag-report-tool/issues/139 (feel free to close that if you don't see other tweaks)
