### ISSUE TITLE
[minor] awkward border around H1 when page is selected

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-atag-report-tool#73]
In Chrome:

1. Use navigation to go to any page, such as "A.3"
2. A border appears around H1 "ATAG REPORT TOOL (3/8) UI operable"

This border does not seem intentional.

**Comment by hidde** [comment]
Under the hood, the `h1` receives focus to make the screenreader experience better in this single page application. 

It isn't an interactive element, so one could say it is “hacky” to give it focus, but it does seem very effective, because we know each “page” has an `h1`, and that `h1` best summarises the “page” one has just navigated to.

What I could do is remove the styling for focused `h1`s, and interpret WCAG `2.4.7` as only applicable to focusing _interactive elements_, what do you think?

**Comment by nitedog** [comment]
I don't know exactly, it just looks odd to me. Also not sure about best practice on moving focus in this particular situation.

**Comment by hidde** [comment]
This method is one of the possible solutions Gatsby user tested (described in [User testing accessible routing](https://www.gatsbyjs.org/blog/2019-07-11-user-testing-accessible-client-routing/)), and found best for screen reader users:

> Focusing on a heading was found to be the best experience, as it would save time and make it clear what happened.

For users of voice navigation, the focus indicator did seem useful: 

> moving focus and showing a visible focus outline was helpful as it showed an element of interest and guided their attention to the relevant content 

For users of switch controls they seemed useful, but also confusing.

> The visible focus indicators were useful, though they added that focus outlines on inoperable elements can be confusing.

*** 

And then there's [2.4.7](https://www.w3.org/WAI/WCAG21/quickref/#focus-visible), which says every “keyboard operable user interface” requires visible focus.

Given all this, I will interpret application of [2.4.7](https://www.w3.org/WAI/WCAG21/quickref/#focus-visible) like this: the heading is not a “keyboard operable user interface”, so “Focus visible” does not apply to it. While visible focus in this case could help some, it can confuse or feel awkward to others.

I have removed the visible focus with a comment in the code to explain, more than happy to revisit at a later point.
