### ISSUE TITLE
[Medium] The preview links should appear after the edit box in the tab order

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-atag-report-tool#77]
While navigating through the elements in "Your evaluation" step, we find is:

* The link to the SC.
* The link to implementing the SC.
* The combo to set the result for the SC.
* A link for the Markdown syntax.
* The preview link.
* The edit box for the Markdown text.

It seems more logical to me that the preview for each of the SCs appears after the edit box, as users may first write some text and then they might want to check if what they wrote shows up correctly.

**Comment by hidde** [comment]
I have just updated this so that the links are later in the source order. 

This should put them later in tab order, but as this is done in CSS and there some spec discussion around whether tab order should match CSS-influenced order, it may not be the case in some browsers. Have verified in Firefox, Chrome and Safari.
