### ISSUE TITLE
Move explanation of Markdown syntax to overview page

### ISSUE THREAD

**Issue by hidde** [w3c/wai-atag-report-tool#89]
Every SC has a link to Markdown syntax. Should we move this to the overview page?

cc @nitedog

**Comment by nitedog** [comment]
Apparently this is also not just Markdown but also HTML. This might not be clear to everyone.

In any case, I think we should separate the information that these text areas accept Markdown and HTML code from the functionality of previewing the entries in the report. Conceptually these seem to be separate things to me, whether the information pieces goes onto the overview page or not.

**Comment by slhenry** [comment]
+ for deleting "Markdown supported" from every SC and putting in "How to Use this Tool"

**Comment by hidde** [comment]
@slhenry  I think “Markdown supported” is a useful thing to display with the textarea as it explains what can be inputted in the textarea. One of my favourite Markdown editors is this very website. Instead of displaying the text ‘Markdown supported’, there is an icon with a tooltip, I think just displaying the text is more clear.

@nitedog I believe in most implementations Markdown is a superset of HTML. This may be useful for users of our tool too.  

I have removed the link to the syntax (which was “syntax” with every SC, I admit that was a bit much), and added a separator between “Markdown supported” and “View in report”. I feel they are both bits of meta information, and agree they are conceptually separate bits of meta information. 

<img width="326" alt="Markdown supported, a vertically centered, then a link Preview in report" src="https://user-images.githubusercontent.com/178782/80251263-9bb75380-8675-11ea-870e-4af27ad4b184.png">

**Comment by slhenry** [comment]
I'm not convinced that we want "Markdown supported" 52 times in this tool. (especially since it's a nice-to-have, not important feature)

I do think would be good in the Tips or "How to Use this Tool" to clarify if can use HTML. I *think* (yet don't have data to back it up) that more potential users of this tool know HTML than Markdown.

**Comment by hidde** [comment]
It does appear 52 times, but… it is:

* in a smaller font
* not in the `<label>` for the textarea

With that I'm hoping it to be, at the same time, not disruptive, and helpful.

If the information if only in the “How to use the tool”, I believe many people will miss it. Arguably, we want to encourage people to markup up their observations so that they can make them more helpful.

For instance, compare: 

* a report that has just the problems in plain text
* a report that links out to resources for each SC that is not met, code examples and lists for clarity

If we can somehow encourage the latter, I think we would encourage reports that are more actionable, and more action means an increased change fo the web to become more accessible web.

**Comment by hidde** [comment]
Suggestion: 

- use icon instead of 'Markdown supported', links to homepage explanation
- say 'View in report'

**Comment by hidde** [comment]
In current version, this Overview explanation was added: 

> You can format your evaluation with Markdown, so that you can use lists, links and code examples. 

Visually, the Markdown supported text is now an icon. Semantically, it is now a link to the explanation on the homepage.

<img width="596" alt="Screenshot 2020-05-05 at 16 08 36" src="https://user-images.githubusercontent.com/178782/81075459-af22b400-8eea-11ea-8096-6a8247233579.png">

**Comment by bakkenb** [comment]
So, as a non-coder. The previous version was clear to me because it said "markdown supported" and I knew what that meant, even though I only know a few markdown techniques. And then the "view in report" made sense because it was next to "markdown supported." My mind said, "oh! I can add markdown to these fields and it will work! And OH! I can get a quick preview of it to see if I coded the markdown correctly. Cool!"

I looked at the newest version before reading this issue...
Now that there is an "M" icon, I didn't have a clue what that was for until I clicked on it. It jumped off the page and took me a moment to realize that I was back on the overview page with some instruction detail and needed to go back to the menu to get back to where I was. Secondly, the M icon was separated from the "view in report" link so the connection of "add markdown and then go view it to see if it is the way you want it" was lost.

I like the first implementation better, having it repeated over and over visually (but not verbally by a screen reader) did seem like a bit much, but I quickly started ignoring that it was there when I knew what it meant. 

Not sure what preference I like, just trying to give a user experience anecdote.

**Comment by slhenry** [comment]
I also think that the [M^] icon is more visually distracting.

**Comment by hidde** [comment]
> Not sure what preference I like, just trying to give a user experience anecdote.

Thanks, Brent, this is very useful! 

> I like the first implementation better, having it repeated over and over visually (but not verbally by a screen reader) did seem like a bit much, but I quickly started ignoring that it was there when I knew what it meant. 

Easily ignored is what I was going for! I think the same goes for the icon, but harder to understand at first, so if the text is:

* just as easily ignored
* clearer, because connects with 'View in report'

and, as Shawn says:

> I also think that the [M^] icon is more visually distracting. 
 
I feel we should just revert that change and have the text there.

**Comment by slhenry** [comment]
> I feel we should just revert that change and have the text there.

+1 to no icon

-1 to repeated "Markdown supported" 52 times.

>  having it repeated over and over visually (but not verbally by a screen reader) did seem like a bit much

I think it's not an equivalent experience if not available to screen reader.

I'm still missing why it's so important to repeat 52 times. It seems like it's not essential information, and can just be in the How to Use section.

In How to Use this Tool:
> You can format your evaluation with Markdown, so that you can use lists, links and code examples.

I think these needs a bit more explanation. e.g., to clarify that you can use Markdown in the Observations text boxes.

What about HTML?

Also, I'm not sure how many people know "Markdown". Maybe good to link to explanation?

**Comment by hidde** [comment]
> I think it's not an equivalent experience if not available to screen reader.

It is available, just not in the label, so less jarring.

> I'm still missing why it's so important to repeat 52 times. It seems like it's not essential information, and can just be in the How to Use section.

Just like we repeat the `textarea` and the text 'Observation' 52 times.

> I think these needs a bit more explanation. e.g., to clarify that you can use Markdown in the Observations text boxes.

Good point. It currently only works in those.

> What about HTML?

For me, this follows from Markdown.

> Also, I'm not sure how many people know "Markdown". Maybe good to link to explanation?

There is a link to Wikipedia which has syntax information, sorry had not included that above in this issue, but it is in the implementation.

**Comment by mpalmersg** [comment]
I can see both sides of this argument. Having "Markdown supported" 52 times seems excessive, however as someone who regularly needs to refresh their memory around markdown I would probably appreciate the information close at hand.

**Comment by daniel-montalvo** [comment]
I mildly prefer to have the Markdown explanation only in the Overview page, given current functionality. We would save one tab stop per each of the 52 times it appears, and that is a great saving in my view.

Note that in the GitHub ecosystem what they say is "Styling with Markdown is supported -- Learn about Styling with Markdown. I see there a slight difference with our tool in that they are promoting their own resources to learn about Markdown rather than only saying they support it.

If the current "Markdown Supported" link in the ART would take you to a Markdown cheatsheet, I would agree with @mpalmersg that it would be useful for those who need to refresh their Markdown skills often. So to make it worth being there in each of the textareas I would change its functionality and make it link to a Markdown cheatsheet. Otherwise, I would remove it from the textarea.

**Comment by daniel-montalvo** [comment]
Some suggestions to the MarkDown phrasing.

Current:

> You can format your evaluation with Markdown, so that you can use lists, links and code examples easier and quicker.

Suggested:

In addition to HTML, You can format your evaluation with Markdown, so that you can use lists, links and code examples.

* I think we need to make clear that HTML can also be used. From comments on this thread, I guess once a Markdown parser is implemented, HTML markup is also treated, but that might not be so evident for many users.
* You could already use lists, links, and code examples without MarkDown. Its added value (which I agree on), comes as it is much more quicker, easier to read and write than HTML is.

**Comment by bakkenb** [comment]
I agree with both of Daniel's comments above. Very good to hear perspective from screen reader use case. I am leaning more to this style of implementation.

**Comment by AndrewArch** [comment]
Overall comments from colleagues:

- Q7 Markdown on observations boxes
-- Other: it is a helpful reminder but it links back to the Overview > Tips section, which is unexpected. It might be more helpful to provide a link to some basic Markdown styles like lists, links, etc? If so, the link text should probably be ‘Markdown help’ or similar.

- Q8 Markdown reference on the Overview page
-- Very good as is – basic with a link to more information. 

- Q9 Display of Markdown prompt
-- The location of the prompt is good, especially if it becomes a link to help information. We’d prefer an icon but a text link is fine.

- Q10 Parser support
-- “I agree with the editor not to promote the HTML support” Markdown should provide what’s needed to make a good report. It seems like the security risk outweighs the benefits. Is it possible to remove the HTML support? If someone needs a lot of HTML in their observations, that seems beyond the scope of this tool.

**Comment by hidde** [comment]
Many thanks for all of your comments.

It seems the 52 tab stops (or 4-6 per page) may be worthwhile if this links to something useful, and the overview page is not the most useful destination for the link. 

What about this: 

<img width="548" alt="Label observations, text Markdown supported, icon question mark, link view in report" src="https://user-images.githubusercontent.com/178782/81969688-a8005200-961e-11ea-845f-21a4c1fcb98d.png">

Where the question mark icon would link to a cheatsheet on our page (easiest to build) or open a tooltip with the most used and “will benefit accessibility conformance reports most” syntax, such as links, lists, emphasis and code examples.

> It seems like the security risk outweighs the benefits. Is it possible to remove the HTML support? 

It is not at the moment, but since we don't send/receive data on our servers, I feel this is acceptable.
