### ISSUE TITLE
For multi-level SCs, allow for input of level that is met

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#95]
Several individual SCs can be met at level A, AA, or AAA. e.g.,:
> A.1.1.1 Web-Based Accessible (WCAG): If the authoring tool contains web-based user interfaces, then those web-based user interfaces meet the WCAG 2.0 success criteria. (Level A to meet WCAG 2.0 Level A success criteria; Level AA to meet WCAG 2.0 Level A and AA success criteria; Level AAA to meet all WCAG 2.0 success criteria)

I think this report needs to indicate which level for each of these SC.

That is, if the report says A.1.1.1 is "Passed", some users will want to know if it passes at Level A or Level AA.

I know this will complicate the UI, yet, I think it's important. (Happy to be convinced otherwise. :-)

**Comment by hidde** [comment]
Nooooo… I had forgotten about this! You are, of course, right. 

One idea… might we request people to ‘simply’ write the level in the observations box?

**Comment by hidde** [comment]
I've marked it a bug, because it potentially blocks users from using the current interface to do an ATAG evaluation.

**Comment by slhenry** [comment]
> One idea… might we request people to ‘simply’ write the level in the observations box?

Of course, we _could_ ; however, I think that some users of the tool and of the resulting reports will want the data more clearly, e.g., they might want summaries based on level.

Not sure whether this is requirement for MVP, or enhancement for future iteration?

**Comment by hidde** [comment]
@nitedog do you think MVP or enhancement for future iteration?

**Comment by nitedog** [comment]
I'm wondering if there are ways to reduce the effort to get this into the first version.

Do you think we could have just one "conformance target" option in the metadata/start tab (like we have in the WCAG-EM Report Tool)? When someone sets "ATAG Level XYZ", then the relevant SC targets are adapted accordingly. The default would be Level AA.

**Comment by hidde** [comment]
We now have 'Conformance target'. 

In the current implementation, single-level SCs are only displayed if within conformance target (otherwise in expand/collapse), and multi-level SCs are *always* displayed.

Proposal to resolve this issue: change nothing and let people write the conformance level in the Observations text box.

**Comment by hidde** [comment]
Proposal from @nitedog: save 'evaluated as level' property separate from 'level' property and, for multi-level SCs, set it to the conformance target level by default (but make it overridable).

This will take more time than doing nothing, but it will improve the generated reports and improve the data we may get in the Authoring Tools List.

**Comment by hidde** [comment]
@nitedog @slhenry I've implemented this almost as @nitedog suggested, see [preview](https://atag-report-tool-git-support-multi-level-scs-better.hdv.now.sh/principle/5).

* each evaluation entry now has the `evaluatedLevel` property, which is the same as the level for all SCs, except for multi-level SCs, where it defaults to “Level AA”
* multi-level SCs now display 'Evaluate as' selection box, where the default can be changed as needed

<img width="168" alt="label Evaluate As with option list that has Level AA selected" src="https://user-images.githubusercontent.com/178782/83019523-6365b500-a027-11ea-8323-d7eabcf8c24c.png">

One subtle difference to original proposal: changing conformance level does not update the defaults. I recommend we don't implement that, because it requires spaghetti-like updates to the code, affecting long term maintainability, for little gain.

Please let me know if this satisfies your requirements and I'll merge the pull request.

**Comment by hidde** [comment]
Comment from @nitedog: add `(Level X)` to table of results on results page, where X is the “evaluated” level.

**Comment by nitedog** [comment]
Works for me with the fix described above.

**Comment by hidde** [comment]
Hidde to add, on Report page, the words “evaluated as” to level indicator if it is a multi-level SC.
