### ISSUE TITLE
user flow for saving OK?

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-atag-report-tool#99]
1. open tool online and do some things
2. save locally
3. close browser, go do other things
4. open local HTML file, continue with evaluation

Is this how you envision people using tool, and this will work OK?

**Comment by hidde** [comment]
It depends on what you save locally.

If JSON, you will have a JSON file and will need to come back to the report tool, import it and continue.

If HTML (this feature is yet to be built 😄), you could edit the file locally, but you would then not have the report tool to ”help” you. Note this would be just the results table. This may be fine if adjusting two words and a grammar mistake, but probably not helpful if you had just started, because you can then not benefit from seeing the SC texts, having your process broken up into principles, writing Markdown, etc. 

So: JSON is for importing/exporting, HTML gives you a copy of the results that you can do with what you want.

**Comment by nitedog** [comment]
I would say typical workflows would more likely be:

1. open tool online and do some things
2. save/download as JSON file
3. close the browser or send JSON to a colleague
4. load/open the JSON file and continue working
5. rinse and repeat as needed
6. save/download HTML file for mostly completed report
7. customize the HTML (eg. styling, corporate logo, etc. but not really continue evaluation)

This is mostly derived from WCAG-EM Report Tool. What do others think?

**Comment by slhenry** [comment]
Role-playing real user, I read on the first page: "Note: this evaluation happens on your computer, no data is sent to us. To save the report on your computer, use Ctrl/⌘ (Command) + S."

So that's what I did.

If you want users to do otherwise, need to change the instructions.

**Comment by hidde** [comment]
I find “To save the report on your computer, use Ctrl/⌘ (Command) + S.” confusing, too. Will remove.

Have replaced with: 

> To save the report on your computer, export it to HTML or JSON on the Report page.

Which better matches what this tool does. Depends on #72, which I am working on separately and would go into the first release.
